spring:
  datasource:
    url: jdbc:h2:mem:test
    username: ximi
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        show_sql: true
        format_sql: true




