server:
  port: 8030

spring:
  application:
    name: eureka-train-customer

eureka:

  instance:
    hostname: localhost
    instanceId: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

  client:
    service-url:
      defaultZone: http://localhost:8010/eureka/

