server:
  port: 8030

spring:
  application:
    name: train-customer

  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        #consul 部署在本地环境的docker中,docker 通过192.168.99.1来访问宿主机#
        health-check-url: http://192.168.99.1:8030/actuator/health
        prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic

management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  circuitbreaker:   ###断路器配置
    backends:
      teacher:
        failureRateThreshold: 50
        waitDurationInOpenState : 10000
        ringBufferSizeInHalfOpenState: 5
        ringBufferSizeInClosedState : 3
        eventConsumerBufferSize: 10

  bulkhead:   ###并发访问配置
    backends:
      teacher:
        maxConcurrentCalls: 3
        maxWaitTime : 100

  retry:
    backends:
      teacher:
        maxAttempts: 3
        waitDuration: 500


