spring:
  redis:
    host: 192.168.99.100
    port: 6379

  datasource:
    username: ximi
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC

  mybatis:
    type-aliases-package: com.ximi.mybatis.entity
    type-handlers-package:  com.ximi.mybatis.handler
    mapper-locations: classpath*:/mapper/**/*.xml

