server:
  port: 8020

spring:
  application:
    name: train-service

  datasource:
    username: ximi
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC&allowPublicKeyRetrieval=true

  jpa:
    properties:
      hibernate:
        show_sql: false
        format_sql: false

  cloud:
    consul:
      host: 192.168.99.100
      port: 8500
      discovery:
        health-check-url: http://192.168.99.1:8020/actuator/health
        prefer-ip-address: true

#      config:
#        enabled: true
#        prefix: config
#        default-context: train-service
#        format: YAML
#        fail-fast: false

  rabbitmq:
    host: 192.168.99.100
    port: 5672
    username: spring
    password: spring

  zipkin:
    base-url: http://192.168.99.100:9411/
    discovery-client-enabled: false
    sender:
      type: web
    compression:
      enabled: false

  sleuth:
    sampler:
      probability: 1


management:
  endpoint:
    health:
      show-details: always

  endpoints:
    web:
      exposure:
        include: '*'

resilience4j:
  ratelimiter:
    instances:
      teacher:
        limitForPeriod: 3
        limitRefreshPeriod: 10s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100

      student:
        limitForPeriod: 3
        limitRefreshPeriod: 5s
        timeoutDuration: 0
        registerHealthIndicator: true
        eventConsumerBufferSize: 100
