spring:
  datasource:
    url: jdbc:mysql://192.168.99.100:3306/test?useUnicode=true&useSSL=false&characterEncoding=utf8&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: ximi
    password: 123456

  redis:
    host: 192.168.99.100
    port: 6379